### ISSUE TITLE
I can't seem to get atom to auto-select this for .prisma files

### ISSUE THREAD

**Issue by jwld** [victorhqc/language-prisma#2] opened 2020-01-17 22:34 UTC
Thanks for the package, works great otherwise.

Can you think of why it might not be being auto-detected?

If I have `language-graphql` installed `.prisma` files are auto-set as graphql, but even if I uninstall that one it's just defaulting to `plain text`.

**Comment by victorhqc** [comment] 2020-01-21 10:14
Hello @jwld! That's strange, could you share some prisma file to reproduce the issue? I also have `language-graphql` installed

**Comment by jwld** [comment] 2020-01-22 10:42
Yes - my file is called `schema.prisma` and looks like this:
```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Album {
  artists   Artist[]
  imageUrl  String?
  spotifyId String? @unique
  title     String
  year      Int
  // meta
  createdAt DateTime @default(now())
  id        String   @default(cuid()) @id
  updatedAt DateTime @updatedAt
}

model Artist {
  albums    Album[]
  imageUrl  String?
  name      String
  spotifyId String? @unique
  // meta
  createdAt DateTime @default(now())
  id        String   @default(cuid()) @id
  updatedAt DateTime @updatedAt
}

```

**Comment by victorhqc** [comment] 2020-01-22 15:36
Very strange, I just tried it and it works for me. I tried uninstalling `language-prisma` and reinstalling again. Then I went to see this package: `language-graphql` and they have prisma support as well, but for me it renders it correctly (with `language-prisma` for prisma files).

<img width="325" alt="Screenshot 2020-01-22 at 16 32 57" src="https://user-images.githubusercontent.com/726113/72907902-01bdd300-3d35-11ea-8d98-23dcf8388244.png">

Could you try this:

1. uninstalling both packages (`language-prisma` & `language-graphql`)
1. close Atom (make sure is properly closed in Mac)
1. opening Atom again
1. Installing language-prisma
1. Check if file works
1. Repeat but install both packages again

Just want to be sure if it's some weird edge case or I'm missing something, not sure how Atom prioritizes languages that cover the same extension type.

**Comment by jwld** [comment] 2020-01-27 08:44
Thanks - I'm seeing an error when trying to reinstall at the moment. Here's the full output:
```
Packages are published to atom.io and are installed to /Users/blah/.atom/packages
Installing “language-prisma@0.1.0” failed.Hide output…

> tree-sitter-prisma@1.0.0 install /private/var/folders/sz/_kv40v1s7g1by6cl1b0prjtc0000gn/T/apm-install-dir-120027-38929-6ji7sd.0wzyn/node_modules/language-prisma/node_modules/tree-sitter-prisma
> node-gyp rebuild


No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/sz/_kv40v1s7g1by6cl1b0prjtc0000gn/T/apm-install-dir-120027-38929-6ji7sd.0wzyn/node_modules/language-prisma/node_modules/tree-sitter-prisma
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/sz/_kv40v1s7g1by6cl1b0prjtc0000gn/T/apm-install-dir-120027-38929-6ji7sd.0wzyn/package.json'
npm WARN apm-install-dir-120027-38929-6ji7sd.0wzyn No description
npm WARN apm-install-dir-120027-38929-6ji7sd.0wzyn No repository field.
npm WARN apm-install-dir-120027-38929-6ji7sd.0wzyn No README data
npm WARN apm-install-dir-120027-38929-6ji7sd.0wzyn No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-prisma@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-prisma@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blah/.atom/.apm/_logs/2020-01-27T08_39_02_635Z-debug.log
```

Side note - I uninstalled `language-graphql` first, and even then atom was just defaulting to `Plain Text` rather than `Prisma` for `.prisma` files. Haven't managed to do a fresh install of `language-prisma` yet though because of the error above.

**Comment by victorhqc** [comment] 2020-01-27 08:52
Ah this is related to the native module the package requires, could you run this and try again?

```sh
xcode-select --install
```

**Comment by jwld** [comment] 2020-01-27 10:47
Ok all sorted! I actually found the issue in my core preferences - I had "Use Tree Sitter Parsers" toggled off. That seems to stop the package working.

**Comment by victorhqc** [comment] 2020-01-27 15:20
Ah nice! glad it was sorted out 😄

**Closed as completed** 2020-01-27 15:20 UTC
